### ISSUE TITLE
Error loading colour scheme, happens as soon as the package is installed

### ISSUE THREAD

**Issue by stradicat** [smhg/sublime-suncycle#12]
Hi,

I just installed the suncycle package, and I constantly get the following error message:

> Error loading colour scheme Packages/User/Solarized (Light) (SL).tmTheme: Unable to open Packages/User/Solarized (Light) (SL).tmTheme

This error message keeps popping up during the usage of the editor, and color highlighting stops working.

**Comment by smhg** [comment]
Hi Dennis, I'll try to have a look at it.
Since I don't use the package anymore myself, anyone taking over its maintenance would be awesome. You don't happen to be interested?
The code base is small and I created it without knowing 2 lines of Python.

**Comment by smhg** [comment]
I have to be honest to you and myself: I won't find the time to look into this.
Additionally, I've added an unmaintained message to the Readme.

The issue you have can't be hard to solve though.
Feel free to send a PR or take over the project. Those things I'll handle of course.

**Comment by stradicat** [comment]
I had been looking into going with Sublime, but fell back into Emacs thanks to Spacemacs.

I hope someone can maintain the project, it's a nice feature to have when you achieve your zone around sundown :)
